import 'dart:async';
import 'package:fpdart/fpdart.dart';
import 'package:injectable/injectable.dart';

import '../../../../core/errors/failures.dart';
import '../../domain/entities/task_entity.dart';
import '../../domain/repositories/task_repository.dart';
import '../datasources/task_remote_data_source.dart';
import '../models/task_model.dart';

@LazySingleton(as: TaskRepository)
class TaskRepositoryImpl implements TaskRepository {
  late final TaskRemoteDataSource remoteDataSource;

  TaskRepositoryImpl(this.remoteDataSource);

  @override
  Stream<Either<Failure, List<TaskEntity>>> getTasksStream(String projectId) {
    return remoteDataSource
        .getTasksStream(projectId)
        .transform(
          StreamTransformer<
            List<TaskModel>,
            Either<Failure, List<TaskEntity>>
          >.fromHandlers(
            handleData: (tasks, sink) {
              sink.add(Right<Failure, List<TaskEntity>>(tasks));
            },
            handleError: (error, stack, sink) {
              sink.add(
                Left<Failure, List<TaskEntity>>(
                  ServerFailure(error.toString()),
                ),
              );
            },
          ),
        );
  }

  @override
  Future<Either<Failure, TaskEntity>> createTask({
    required String projectId,
    required String title,
    required String description,
    required DateTime dueDate,
    required String assigneeId,
  }) async {
    try {
      final newTask = TaskModel(
        id: '', // Generated by remote
        projectId: projectId,
        title: title,
        description: description,
        status: TaskStatus.todo,
        dueDate: dueDate,
        assigneeId: assigneeId,
      );
      final result = await remoteDataSource.createTask(newTask);
      return Right(result);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, TaskEntity>> updateTask(TaskEntity task) async {
    try {
      final taskModel = TaskModel.fromEntity(task);
      final result = await remoteDataSource.updateTask(taskModel);
      return Right(result);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }
}
