import 'dart:async';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:fpdart/fpdart.dart';
import 'package:injectable/injectable.dart';

import '../../../../core/errors/failures.dart';
import '../../domain/entities/task_entity.dart';
import '../../domain/entities/comment_entity.dart';
import '../../domain/repositories/task_repository.dart';
import '../datasources/task_remote_data_source.dart';
import '../models/task_model.dart';
import '../models/comment_model.dart';

@LazySingleton(as: TaskRepository)
class TaskRepositoryImpl implements TaskRepository {
  late final TaskRemoteDataSource remoteDataSource;
  late final FirebaseAuth firebaseAuth;

  TaskRepositoryImpl(this.remoteDataSource) {
    firebaseAuth = FirebaseAuth.instance;
  }

  @override
  Stream<Either<Failure, List<TaskEntity>>> getTasksStream(String projectId) {
    return remoteDataSource
        .getTasksStream(projectId)
        .transform(
          StreamTransformer<
            List<TaskModel>,
            Either<Failure, List<TaskEntity>>
          >.fromHandlers(
            handleData: (tasks, sink) {
              sink.add(Right<Failure, List<TaskEntity>>(tasks));
            },
            handleError: (error, stack, sink) {
              sink.add(
                Left<Failure, List<TaskEntity>>(
                  ServerFailure(error.toString()),
                ),
              );
            },
          ),
        );
  }

  @override
  Future<Either<Failure, TaskEntity>> createTask({
    required String projectId,
    required String title,
    required String description,
    required DateTime dueDate,
    required String assigneeId,
    required TaskPriority priority,
    List<CommentEntity> comments = const [],
  }) async {
    try {
      final currentUserId = firebaseAuth.currentUser?.uid ?? '';
      final newTask = TaskModel(
        id: '', // Generated by remote
        projectId: projectId,
        title: title,
        description: description,
        status: TaskStatus.todo,
        priority: priority,
        dueDate: dueDate,
        assigneeId: assigneeId,
        lastModifiedBy: currentUserId,
        comments: comments,
      );
      final result = await remoteDataSource.createTask(newTask);
      return Right(result);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, TaskEntity>> updateTask(TaskEntity task) async {
    try {
      final currentUserId = firebaseAuth.currentUser?.uid ?? '';
      final updatedTask = task.copyWith(lastModifiedBy: currentUserId);
      final taskModel = TaskModel.fromEntity(updatedTask);
      final result = await remoteDataSource.updateTask(taskModel);
      return Right(result);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> deleteTask(String taskId) async {
    try {
      await remoteDataSource.deleteTask(taskId);
      return const Right(null);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }

  @override
  Future<Either<Failure, CommentEntity>> addComment({
    required String taskId,
    required CommentEntity comment,
  }) async {
    try {
      final commentModel = CommentModel.fromEntity(comment);
      final result = await remoteDataSource.addComment(taskId, commentModel);
      return Right(result);
    } catch (e) {
      return Left(ServerFailure(e.toString()));
    }
  }
}
